name: build test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        #os: [macos-latest]
        #os: [macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      # Install Nix and use that to run our tests so our environment matches exactly.
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      # Run our checks to catch quick issues
      - run: nix flake check

      - name: build & test
        run: nix develop -c zig build test --summary all
